import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { stringify as toYaml } from "yaml";
import { tollboothConfigSchema } from "./config/schema.js";

const rl = createInterface({
	input: process.stdin,
	output: process.stdout,
});

async function ask(question: string, fallback?: string): Promise<string> {
	const suffix = fallback ? ` (${fallback})` : "";
	const answer = (await rl.question(`  ${question}${suffix}: `)).trim();
	if (!answer && fallback) return fallback;
	return answer;
}

async function confirm(question: string): Promise<boolean> {
	const answer = await ask(`${question} [y/N]`);
	return answer.toLowerCase() === "y";
}

export async function runInit() {
	console.log("\n⛩️  tollbooth init — generate a config file\n");

	const configPath = resolve(process.cwd(), "tollbooth.config.yaml");

	// ── Overwrite protection ─────────────────────────────────────────────────
	if (existsSync(configPath)) {
		const overwrite = await confirm(
			"tollbooth.config.yaml already exists. Overwrite?",
		);
		if (!overwrite) {
			console.log("\nAborted.");
			rl.close();
			return;
		}
		console.log();
	}

	// ── Upstreams ────────────────────────────────────────────────────────────
	const upstreams: Record<string, { url: string }> = {};
	let addMore = true;

	while (addMore) {
		const name = await ask(
			`Upstream name${Object.keys(upstreams).length === 0 ? "" : " (or empty to finish)"}`,
		);
		if (!name && Object.keys(upstreams).length > 0) break;
		if (!name) {
			console.log("  At least one upstream is required.\n");
			continue;
		}
		const url = await ask("Upstream API URL");
		if (!url) {
			console.log("  URL is required.\n");
			continue;
		}
		upstreams[name] = { url };
		console.log();
		if (Object.keys(upstreams).length > 0) {
			addMore = await confirm("Add another upstream?");
			if (addMore) console.log();
		}
	}

	console.log();

	// ── Routes ───────────────────────────────────────────────────────────────
	const upstreamNames = Object.keys(upstreams);
	const routes: Record<string, { upstream: string; price: string }> = {};
	let addMoreRoutes = true;

	while (addMoreRoutes) {
		const methodAndPath = await ask(
			"Route method and path (e.g. POST /v1/chat/completions)",
		);
		if (!methodAndPath && Object.keys(routes).length > 0) break;
		if (!methodAndPath) {
			console.log("  At least one route is required.\n");
			continue;
		}

		let upstream: string;
		if (upstreamNames.length === 1) {
			upstream = upstreamNames[0];
		} else {
			upstream = await ask(`Upstream [${upstreamNames.join(", ")}]`);
			if (!upstreamNames.includes(upstream)) {
				console.log(`  Must be one of: ${upstreamNames.join(", ")}\n`);
				continue;
			}
		}

		const price = await ask("Price per request", "$0.01");
		routes[methodAndPath] = { upstream, price };
		console.log();

		addMoreRoutes = await confirm("Add another route?");
		if (addMoreRoutes) console.log();
	}

	console.log();

	// ── Payment ──────────────────────────────────────────────────────────────
	const network = await ask("Network", "base-sepolia");
	const asset = await ask("Asset", "USDC");
	const wallet = await ask("Wallet address");

	if (!wallet) {
		console.log("\n  Wallet address is required.");
		rl.close();
		process.exit(1);
	}

	rl.close();

	// ── Build config ─────────────────────────────────────────────────────────
	const raw = {
		gateway: {
			port: 3000,
			discovery: true,
		},
		wallets: {
			[network]: wallet,
		},
		accepts: [{ asset, network }],
		defaults: {
			price: "$0.001",
			timeout: 60,
		},
		upstreams,
		routes,
	};

	// ── Validate ─────────────────────────────────────────────────────────────
	const result = tollboothConfigSchema.safeParse(raw);
	if (!result.success) {
		const issues = result.error.issues
			.map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
			.join("\n");
		console.error(`\n❌ Generated config is invalid:\n${issues}`);
		process.exit(1);
	}

	// ── Write YAML ───────────────────────────────────────────────────────────
	const header = `# tollbooth.config.yaml — generated by \`tollbooth init\`\n\n`;
	const yaml = toYaml(raw, { lineWidth: 0 });
	writeFileSync(configPath, header + yaml, "utf-8");

	const routeCount = Object.keys(routes).length;
	const upstreamCount = Object.keys(upstreams).length;
	console.log(
		`\n✅ Created tollbooth.config.yaml (${upstreamCount} upstream(s), ${routeCount} route(s))`,
	);
	console.log("\n  Next steps:");
	console.log("    tollbooth validate   Check the config");
	console.log("    tollbooth start      Start the gateway\n");
}
